### ISSUE TITLE
manque info

### ISSUE THREAD

**Issue by ripoul** [drim-tim/pump-it-up#1]
@Airthee @lucasmart  c'est quoi le site ou il y a les données de test et le sujet ?

**Comment by Airthee** [comment]
You can have more informations at the following url : [CLICK HERE TO BE INFECTED BY THE BIGEST VIRUS EVER](https://www.drivendata.org/competitions/7/pump-it-up-data-mining-the-water-table)

**Comment by ripoul** [comment]
merci
